In [2]:
import pandas as pd
import numpy as np
import pickle

# Integrating Predictions for Random Forest Classifier

In [51]:
#Read in the csv file for all rf predictions
target_preds_rf = pd.read_csv("target_preds_rf.csv", index_col=[0])
btts_preds_rf = pd.read_csv("btts_preds_rf.csv", index_col=[0])
above_preds_rf = pd.read_csv("above_2.5_preds_rf.csv", index_col=[0])

In [13]:
target_preds_rf.head(2)

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,new_opponent_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y,new_opponent_y
0,1,0,2022-08-05,Arsenal,Crystal Palace,W,Arsenal,Crystal Palace,0,0,Crystal Palace,Arsenal,L,Crystal Palace,Arsenal
1,1,0,2022-08-13,Arsenal,Leicester City,W,Arsenal,Leicester City,0,0,Leicester City,Arsenal,L,Leicester City,Arsenal

In [14]:
btts_preds_rf.head(2)

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,new_opponent_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y,new_opponent_y
0,0,1,2022-08-05,Arsenal,Crystal Palace,W,Arsenal,Crystal Palace,0,0,Crystal Palace,Arsenal,L,Crystal Palace,Arsenal
1,1,1,2022-08-13,Arsenal,Leicester City,W,Arsenal,Leicester City,1,1,Leicester City,Arsenal,L,Leicester City,Arsenal

In [15]:
above_preds_rf.head(2)

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,new_opponent_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y,new_opponent_y
0,0,1,2022-08-05,Arsenal,Crystal Palace,W,Arsenal,Crystal Palace,0,0,Crystal Palace,Arsenal,L,Crystal Palace,Arsenal
1,1,1,2022-08-13,Arsenal,Leicester City,W,Arsenal,Leicester City,1,1,Leicester City,Arsenal,L,Leicester City,Arsenal

In [39]:
def set_result_predictions(df):
    df['result_preds'] = df['actual_x']
    df['result_actual'] = df['actual_x']
    
    #Setting predictions
    df.loc[((df['predicted_x'] == 1) & (df['predicted_y'] == 0)), ['result_preds']] = 'X'
    df.loc[((df['predicted_x'] == 0) & (df['predicted_y'] == 1)), ['result_preds']] = 'Y'
    df.loc[((df['predicted_x'] == 0) & (df['predicted_y'] == 0)), ['result_preds']] = 'D'
    df.loc[((df['predicted_x'] == 1) & (df['predicted_y'] == 1)), ['result_preds']] = 'NA'
    
    #Setting results
    df.loc[(df['actual_x'] == 1) , ['result_actual']] = 'X'
    df.loc[(df['actual_y'] == 1) , ['result_actual']] = 'Y'
    df.loc[((df['actual_x'] == 0) & (df['actual_y'] == 0)), ['result_actual']] = 'D'
    
    return df

def set_btts_predictions(df):
    df['btts_preds'] = df['actual_x']
    df['btts_actual'] = df['actual_x']
    
    #Setting predictions
    df.loc[((df['predicted_x'] == 1) & (df['predicted_y'] == 1)), ['btts_preds']] = 'Y'
    df.loc[((df['predicted_x'] == 0) & (df['predicted_y'] == 0)), ['btts_preds']] = 'N'
    df.loc[((df['predicted_x'] == 1) & (df['predicted_y'] == 0)), ['btts_preds']] = 'NA'
    df.loc[((df['predicted_x'] == 0) & (df['predicted_y'] == 1)), ['btts_preds']] = 'NA'
    
    #Setting results
    df.loc[(df['actual_x'] == 1) , ['btts_actual']] = 'Y'
    df.loc[(df['actual_x'] == 0) , ['btts_actual']] = 'N'
    
    return df

def set_above_predictions(df):
    df['above_preds']= df['actual_x']
    df['above_actual'] = df['actual_x']
    
    #Setting predictions
    df.loc[((df['predicted_x'] == 1) & (df['predicted_y'] == 1)), ['above_preds']] = 'Y'
    df.loc[((df['predicted_x'] == 0) & (df['predicted_y'] == 0)), ['above_preds']] = 'N'
    df.loc[((df['predicted_x'] == 1) & (df['predicted_y'] == 0)), ['above_preds']] = 'NA'
    df.loc[((df['predicted_x'] == 0) & (df['predicted_y'] == 1)), ['above_preds']] = 'NA'
    
    #Setting results
    df.loc[(df['actual_x'] == 1) , ['above_actual']] = 'Y'
    df.loc[(df['actual_x'] == 0) , ['above_actual']] = 'N'
    
    return df

In [52]:
target_df = set_result_predictions(target_preds_rf)
target_df.head(3)

,actual_x,predicted_x,date,team_x,opponent_x,result_x,round_x,new_team_x,new_opponent_x,actual_y,predicted_y,team_y,opponent_y,result_y,round_y,new_team_y,new_opponent_y,result_preds,result_actual
0,1,0,2022-08-05,Arsenal,Crystal Palace,W,Matchweek 1,Arsenal,Crystal Palace,0,0,Crystal Palace,Arsenal,L,Matchweek 1,Crystal Palace,Arsenal,D,X
1,1,0,2022-08-13,Arsenal,Leicester City,W,Matchweek 2,Arsenal,Leicester City,0,0,Leicester City,Arsenal,L,Matchweek 2,Leicester City,Arsenal,D,X
2,1,1,2022-08-20,Arsenal,Bournemouth,W,Matchweek 3,Arsenal,Bournemouth,0,0,Bournemouth,Arsenal,L,Matchweek 3,Bournemouth,Arsenal,X,X

In [53]:
btts_df = set_btts_predictions(btts_preds_rf)
btts_df.head(3)

,actual_x,predicted_x,date,team_x,opponent_x,result_x,round_x,new_team_x,new_opponent_x,actual_y,predicted_y,team_y,opponent_y,result_y,round_y,new_team_y,new_opponent_y,btts_preds,btts_actual
0,0,1,2022-08-05,Arsenal,Crystal Palace,W,Matchweek 1,Arsenal,Crystal Palace,0,0,Crystal Palace,Arsenal,L,Matchweek 1,Crystal Palace,Arsenal,NA,N
1,1,1,2022-08-13,Arsenal,Leicester City,W,Matchweek 2,Arsenal,Leicester City,1,1,Leicester City,Arsenal,L,Matchweek 2,Leicester City,Arsenal,Y,Y
2,0,0,2022-08-20,Arsenal,Bournemouth,W,Matchweek 3,Arsenal,Bournemouth,0,1,Bournemouth,Arsenal,L,Matchweek 3,Bournemouth,Arsenal,NA,N

In [54]:
above_df = set_above_predictions(above_preds_rf)
above_df.head(3)

,actual_x,predicted_x,date,team_x,opponent_x,result_x,round_x,new_team_x,new_opponent_x,actual_y,predicted_y,team_y,opponent_y,result_y,round_y,new_team_y,new_opponent_y,above_preds,above_actual
0,0,1,2022-08-05,Arsenal,Crystal Palace,W,Matchweek 1,Arsenal,Crystal Palace,0,0,Crystal Palace,Arsenal,L,Matchweek 1,Crystal Palace,Arsenal,NA,N
1,1,1,2022-08-13,Arsenal,Leicester City,W,Matchweek 2,Arsenal,Leicester City,1,1,Leicester City,Arsenal,L,Matchweek 2,Leicester City,Arsenal,Y,Y
2,1,0,2022-08-20,Arsenal,Bournemouth,W,Matchweek 3,Arsenal,Bournemouth,1,0,Bournemouth,Arsenal,L,Matchweek 3,Bournemouth,Arsenal,N,Y

In [56]:
#Create a new dataframe integrating all three predictions and actual outcomes
rf_df = target_df.merge(btts_df[['btts_preds','btts_actual']], left_index = True, right_index = True)
rf_df = rf_df.merge(above_df[['above_preds','above_actual']], left_index = True, right_index = True)
rf_df['x'] = rf_df['team_x']
rf_df['y'] = rf_df['team_y']
rf_df['round'] = rf_df['round_x']
rf_df.head(3)

,actual_x,predicted_x,date,team_x,opponent_x,result_x,round_x,new_team_x,new_opponent_x,actual_y,...,new_opponent_y,result_preds,result_actual,btts_preds,btts_actual,above_preds,above_actual,x,y,round
0,1,0,2022-08-05,Arsenal,Crystal Palace,W,Matchweek 1,Arsenal,Crystal Palace,0,...,Arsenal,D,X,NA,N,NA,N,Arsenal,Crystal Palace,Matchweek 1
1,1,0,2022-08-13,Arsenal,Leicester City,W,Matchweek 2,Arsenal,Leicester City,0,...,Arsenal,D,X,Y,Y,Y,Y,Arsenal,Leicester City,Matchweek 2
2,1,1,2022-08-20,Arsenal,Bournemouth,W,Matchweek 3,Arsenal,Bournemouth,0,...,Arsenal,X,X,NA,N,N,Y,Arsenal,Bournemouth,Matchweek 3

In [57]:
#Save the final file to csv and fill in the odds
#The historical odds has to be filled in manually
rf_df_final = rf_df[["date","round","x","y","result_preds","result_actual","btts_preds","btts_actual","above_preds","above_actual"]]
rf_df_final.to_csv('final_predictions_rf.csv')

In [61]:
#Calculate the objective scores to find the odds
def calculate_betting_odds(df_target, df_btts, df_above):
    
    #Calculating betting odds for a team to win
    win_count = df_target[(df_target["predicted_x"] == 1) & (df_target["predicted_y"] == 0)]
    precision_win = len(win_count[win_count['actual_x'] == 1]) / len(win_count)
    win_odd = round(1/precision_win, 3)

    #Calculating betting odds for teams to draw
    draw_count = df_target[(df_target["predicted_x"] == 0) & (df_target["predicted_y"] == 0)]
    precision_draw = len(draw_count[draw_count['result_x'] == 'D']) / len(draw_count)
    draw_odd = round(1/precision_draw, 3)
    
    #Calculating betting odds for both teams to score
    btts_count = df_btts[(df_btts["predicted_x"] == 1) & (df_btts["predicted_y"] == 1)]
    precision_btts = len(btts_count[(btts_count['actual_x'] == 1) & (btts_count['actual_y'] == 1)]) / len(btts_count)
    btts_odd = round(1/precision_btts, 3)
    
    #Calculating betting odds for not both teams to score
    nbtts_count = df_btts[(df_btts["predicted_x"] == 0) & (df_btts["predicted_y"] == 0)]
    precision_nbtts = len(nbtts_count[(nbtts_count['actual_x'] == 0) & (nbtts_count['actual_y'] == 0)]) / len(btts_count)
    nbtts_odd = round(1/precision_btts, 3)
    
    #Calculating betting odds for above 2.5 goals
    above_count = df_above[(df_above["predicted_x"] == 1) & (df_above["predicted_y"] == 1)]
    precision_above = len(above_count[above_count["actual_x"] == 1]) / len(above_count)
    above_odd = round(1/precision_above, 3)

    #Calculating betting odds for below 2.5 goals
    below_count = df_above[(df_above["predicted_x"] == 0) & (df_above["predicted_y"] == 0)]
    precision_below = len(below_count[below_count["actual_x"] == 0]) / len(below_count)
    below_odd = round(1/precision_below, 3)
    
    #Return all the betting odds
    return win_odd, draw_odd, btts_odd, nbtts_odd, above_odd, below_odd

In [66]:
#Find all the relevant odds
win_odd, draw_odd, btts_odd, nbtts_odd, above_odd, below_odd = calculate_betting_odds(target_preds_rf, btts_preds_rf, above_preds_rf)
print(f"Win Odd: {win_odd}")
print(f"Draw Odd: {draw_odd}")
print(f"BTTS Odd: {btts_odd}")
print(f"NBTTS Odd: {nbtts_odd}")
print(f"Above Odd: {above_odd}")
print(f"Below Odd: {below_odd}")

Win Odd: 1.462
Draw Odd: 4.419
BTTS Odd: 1.5
NBTTS Odd: 1.5
Above Odd: 1.435
Below Odd: 2.6

In [67]:
#Read in the csv file with the odds
rf_df_odds = pd.read_csv("final_predictions_rf_odds.csv")

In [113]:
def calculate_expected_return(df, win_odd, draw_odd, btts_odd, nbtts_odd, above_odd, below_odd):
    #Create new return column to contain all the expected returns and set column types
    expected_returns = []

    #Calculate the return from all the bets according to the odds
    for index, row in df.iterrows():
        expected_return = 0.0
        #Checking the win prediction
        if row['result_preds'] == 'X' and row['x_odds'] >= win_odd:
            #When the prediction hit
            if row['result_actual'] == 'X':
                expected_return = expected_return + row['x_odds'] - 1.0
                
            #When the prediction did not hit
            else:
                expected_return = expected_return - 1.0
        else:
            pass

        #Checking the draw prediction
        if row['result_preds'] == 'D' and row['d_odds'] >= draw_odd:
            #When the prediction hit
            if row['result_actual'] == 'D':
                expected_return = expected_return + row['d_odds'] - 1.0
                
            #When the prediction did not hit
            else:
                expected_return = expected_return - 1.0
        else:
            pass
            
        #Checking the btts prediction
        if row['btts_preds'] == 'Y' and row['btts_odds'] >= btts_odd:
            #When the prediction hit
            if row['btts_actual'] == 'Y':
                expected_return = expected_return + row['btts_odds'] - 1
                
            #When the prediction did not hit
            else:
                expected_return = expected_return - 1.0
        else:
            pass
        
        #Checking the nbtts prediction
        if row['btts_preds'] == 'N' and row['nbtts_odds'] >= nbtts_odd:
            #When the prediction hit
            if row['btts_actual'] == 'N':
                expected_return = expected_return + row['nbtts_odds'] - 1.0
                
            #When the prediction did not hit
            else:
                expected_return = expected_return - 1.0
        else:
            pass
        
        #Checking the above 2.5 prediction
        if row['above_pred'] == 'Y' and row['above_odds'] >= above_odd:
            #When the prediction hit
            if row['above_actual'] == 'Y':
                expected_return = expected_return + row['above_odds'] - 1.0
                
            #When the prediction did not hit
            else:
                expected_return = expected_return - 1.0
        else:
            pass        

        #Checking the below 2.5 prediction
        if row['above_preds'] == 'N' and row['above_odds'] > below_odd:
            #When the prediction hit
            if row['btts_actual'] == 'Y':
                expected_return = expected_return + row['below_odds'] - 1.0
                
            #When the prediction did not hit
            else:
                expected_return = expected_return - 1.0
        else:
            pass
        
        #Add the expected return in the return list
        expected_returns.append(expected_return)
        
        
    return expected_returns

In [114]:
expected_returns = calculate_expected_return(rf_df_odds, win_odd, draw_odd, btts_odd, nbtts_odd, above_odd, below_odd)

In [115]:
#Find the list of all positive and negative returns
positive_returns = []
negative_returns = []
for i in expected_returns:
    if i > 0:
        positive_returns.append(i)
    if i< 0:
        negative_returns.append(i)

In [122]:
print(f"Total Bet Amount Placed   : {len(positive_returns) + len(negative_returns)}")
print(f"Number of Positive Returns: {len(positive_returns)}")
print(f"Average Positive Return   : {round((sum(positive_returns) / len(positive_returns)),3)}")
print(f"Number of Negative Returns: {len(negative_returns)}")
print(f"Average Negative Return   : {round((sum(negative_returns) / len(negative_returns)),3)}")
print(f"Total Expected Return     : {round((sum(positive_returns) + sum(negative_returns)),3)}")
print(f"Expected Profit Margin    : {round((((sum(positive_returns) + sum(negative_returns)) / (len(positive_returns) + len(negative_returns))) * 100),2)}%")

Total Bet Amount Placed   : 158
Number of Positive Returns: 89
Average Positive Return   : 0.971
Number of Negative Returns: 69
Average Negative Return   : -0.956
Total Expected Return     : 20.5
Expected Profit Margin    : 12.97%